# Generated by Django 3.1.3 on 2020-11-07 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('PENDING', 'Pending'), ('ARCHIVED', 'Archived')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('order', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SURVEY', 'Survey'), ('DISCUSSION', 'Discussion'), ('DIARY', 'Diary')], max_length=10)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inclingapi.tile')),
            ],
        ),
    ]
