# Generated by Django 2.2 on 2020-11-08 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inclingapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='launchDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
