# Generated by Django 2.2 on 2020-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclingapi', '0002_tile_launchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
